### ISSUE TITLE
Instead tweaking few changes and create new package, you could have create PR, feature request or any other request. It seems like even docs are same LOL. 😂 

### ISSUE THREAD

**Issue by koiralapankaj7** [tranhuongk/likk_picker#11]
https://pub.dev/packages/drishya_picker

**Comment by tranhuongk** [comment]
I have a lot of changes in your package and i don't think it is suitable for your development direction. that's why i split into another package.

**Comment by koiralapankaj7** [comment]
I would suggest you to go through the licensee policy once. I don't think you have followed license terms and conditions as I can't see any copyright notice in your license.

**Comment by tranhuongk** [comment]
Thank you! I will update my license for this case.
